-- SQLBook: Code
DROP TABLE Cliente;
DROP TABLE Dependente;
DROP TABLE Promocao;
DROP TABLE Pacote;
DROP TABLE Reserva;
DROP TABLE Atividade;
DROP TABLE TipoAtividade;
DROP TABLE Possui;
DROP TABLE Fornecedor;
DROP TABLE ContatoFornecedor;
DROP TABLE FornecedorAlimentacao;
DROP TABLE FornecedorHospedagem;
DROP TABLE FornecedorTransporte;
DROP TABLE FornecedorEvento;
DROP TABLE FrotaTransportadora;

DROP SEQUENCE cliente_seq;
DROP SEQUENCE code_pacote;
DROP SEQUENCE code_atividade;
DROP SEQUENCE seq_codfornecedor;
DROP SEQUENCE seq_fornhosp;
DROP SEQUENCE seq_fornalim;
DROP SEQUENCE seq_fornt;
DROP SEQUENCE seq_fornevent;
DROP SEQUENCE seq_frotatransp;
drop sequence code_promo;
drop sequence codigo;